version: "3.7"

services:
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=gitea
    - MYSQL_USER=gitea
    - MYSQL_PASSWORD=gitea
    - MYSQL_DATABASE=gitea
    networks:
    - giteanet
    volumes:
    - db:/var/lib/mysql
  gitea:
    container_name: gitea
    image: gitea/gitea:latest
    environment:
    - USER_UID=1000
    - USER_GID=1000
    - DB_TYPE=mysql
    - DB_HOST=db:3306
    - DB_NAME=gitea
    - DB_USER=gitea
    - DB_PASSWD=gitea
    restart: always
    networks:
    - giteanet
    volumes:
    - gitea:/data
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    ports:
    - "3000:3000"
    - "222:22"

volumes:
  gitea: {}
  db: {}

networks:
  giteanet:
    name: giteanet
